### ISSUE TITLE
Documentation | Help understanding NAF XML file

### ISSUE THREAD

**Issue by jochemstoel** [vanatteveldt/alpino-server#1]
Hi, I am really glad I found this Alpino server!  Where can I find some docs about the NAF XML file format?  I recognize some abbreviations instinctively but it is unclear to me how to parse the persoonsvorm, onderwerp etc from the file and determine exactly the relationships between words
. 
I will use JavaScript to parse the output from the server "_De banaan is zeer optimistisch_" and want to be able to determine that _(zeer) optimistisch_ is a property of _banaan_ and _zeer_ is a bijwoord describing _optimistisch_.

Or am I expecting too much?

**Comment by vanatteveldt** [comment]
Thanks for your interest. That is absolutely something you can get out of the parse tree. 

The NAF documentation is  available e.g. here: https://research.vu.nl/en/publications/naf-the-nlp-annotation-framework. 

You probably want to get mostly the part of speech (from the term layer) and the dependencies. 

(cc @antske because she knows more about the NAF side)

**Comment by jochemstoel** [comment]
Thanks. I might be completely blind but where on that page is the content? I was expecting something like a reference or PDF file to read.

**Comment by vanatteveldt** [comment]
Sorry, my bad, I thought it would link to the report directly. 

Actually, maybe their github is simply the best source: https://github.com/newsreader/NAF
